apiVersion: apps/v1
kind: Deployment
metadata:
  name: ecommerce-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ecommerce-backend
  template:
    metadata:
      labels:
        app: ecommerce-backend
    spec:
      containers:
        - name: backend
          image: shivam0708/ecommerce-backend:2
          ports:
            - containerPort: 5000
          env:
            - name: APP_NAME
              valueFrom:
                configMapKeyRef:
                  name: ecommerce-backend-config
                  key: APP_NAME
            - name: ENVIRONMENT
              valueFrom:
                configMapKeyRef:
                  name: ecommerce-backend-config
                  key: ENVIRONMENT
            - name: DB_HOST
              value: postgres
            - name: DB_PORT
              value: "5432"
            - name: DB_NAME
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_DB
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_USER
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_PASSWORD

---
apiVersion: v1
kind: Service
metadata:
  name: ecommerce-backend
spec:
  selector:
    app: ecommerce-backend
  ports:
    - port: 5000
      targetPort: 5000
  type: ClusterIP
